services:
  app:
    build:
      context: .
    working_dir: /app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
volumes:
  node_modules:
